### ISSUE TITLE
http://insanityjam.com/ is no longer active

### ISSUE THREAD

**Issue by Spaxe** [AlamantusGameDev/GameIdeaGenerator#1]
Is there an online area that this can be hosted at?

**Comment by Alamantus** [comment]
Yes! This is actually hosted here now:

https://alamantus.gitlab.io/GameIdeaGenerator

**Comment by Spaxe** [comment]
Beautiful, thank you.

May I suggest adding that link to the repo URL, and the README itself? (I can't pull request to update the repo URL.)

**Comment by Alamantus** [comment]
Yeah, I haven't updated this repo in a long time—as the new link suggests, it's on GitLab now.

But I'll update the readme here as soon as I can to point to the right place!

**Comment by Alamantus** [comment]
I've updated the README, and I'm actually going to go ahead and archive this repo since it is no longer maintained here.
